test_runner:
  report_dir: ./reports

wired_pc:
  host: 100.1.1.10
  ssh_port: 22
  user: root
  password: ~
  interface: eth1

sta:
  host: 127.0.0.1
  ssh_port: 22
  user: root
  password: ~
  transport:
    type: radio
    interface: wlan0mon

sniffer:
  host: ""
  ssh_port: 22
  user: root
  password: ~
  interface: wlan0mon

ap:
  telnet:
    host: 100.1.1.1
    port: 23
  serial:
    enable: false
    mode: local
    port: /dev/ttyUSB0
    baudrate: 115200
